import type { ChecklistDocument } from '@/types/checklist';
import type { ChecklistSession } from '@/types/session';
import { getFailedItems, getOverallProgress } from './selectors';

export function buildMarkdownReport(doc: ChecklistDocument, session: ChecklistSession): string {
  const failed = getFailedItems(doc, session);
  const progress = getOverallProgress(doc, session);
  const date = new Date(session.startedAt).toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });

  const lines: string[] = [
    `# Tesla Delivery Inspection Report`,
    ``,
    `**Model:** ${doc.model.replace('-', ' ').replace(/\b\w/g, (c) => c.toUpperCase())}  `,
    `**Date:** ${date}  `,
    `**Completion:** ${progress}%  `,
    `**Issues found:** ${failed.length}`,
    ``,
  ];

  if (failed.length === 0) {
    lines.push('_No issues logged._');
  } else {
    lines.push('## Issues');
    lines.push('');
    failed.forEach((item, i) => {
      const severity = item.state.severity ?? item.state.severity ?? 'unspecified';
      lines.push(`### ${i + 1}. ${item.title}`);
      lines.push(`**Phase:** ${item.phaseTitle}  `);
      lines.push(`**Severity:** ${severity.charAt(0).toUpperCase() + severity.slice(1)}  `);
      if (item.state.note) {
        lines.push(`**Note:** ${item.state.note}  `);
      }
      lines.push('');
    });
  }

  lines.push('---');
  lines.push('_Generated by Tesla Delivery Companion_');

  return lines.join('\n');
}

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}
